"use client";
import {useEffect,useMemo,useState} from "react";

const experience=[
{company:"Sprouts AI",role:"Software Engineer · Applied AI & Agentic Platforms",place:"Chicago, IL",date:"Mar 2025 — Present",bullets:[
"Built AI-powered platforms in Python/FastAPI, including a chatbot reasoning over internal docs, letting engineers explore, analyze, and act on complex program data via RAG retrieval pipelines (embeddings, pgvector), cutting lookup time by 60%.",
"Developed agentic pipelines with modern AI/agent frameworks (LangGraph, function calling, MCP tool-use patterns) automating multi-step research and analysis while keeping engineers in the loop to steer and validate, saving 15+ hours per week.",
"Created evaluation pipelines for AI system outputs, measuring quality through automated evals and human feedback loops, raising end-to-end answer accuracy from 72% to 91% across production workloads.",
"Designed data infrastructure bringing together diverse knowledge sources (PostgreSQL, S3, internal docs) with appropriate access controls, making the right context available to LLMs and engineers at the right time.",
"Shipped CI-integrated analysis and background monitoring for continuous, automated intelligence, surfacing regressions via a macOS menu-bar client (SwiftUI/AppKit) and dashboards, reducing production incidents by 35%."
]},
{company:"Resilience Inc",role:"Software Engineer · Backend & Data Platforms",place:"Chicago, IL",date:"Aug 2023 — Mar 2025",bullets:[
"Shipped an iOS client application (Swift, SwiftUI, UIKit, Core Data) backed by Python/TypeScript services and data pipelines for 10K+ students, applying MVVM architecture and API design that cut integration complexity by 40%.",
"Built reproducible analysis workflows with full provenance tracking for student-outcome analytics, so insights could be trusted, iterated on, and shared across engineering, design, and research disciplines.",
"Created internal developer tools and CLIs that engineers relied on daily for data inspection and deployment, cutting manual operations time by 50%.",
"Designed collaboration systems helping cross-functional teams (SW, design, human factors researchers) accumulate and leverage shared institutional knowledge, translating data challenges into tooling that compounded in value over releases.",
"Shipped iteratively within a large, established codebase using CI/CD (GitHub Actions) and automated testing, sustaining zero-downtime daily deploys with 45% fewer rollbacks."
]},
{company:"Tata Steel",role:"Software Engineer · Data Infrastructure & Platforms",place:"",date:"Apr 2018 — Aug 2023",bullets:[
"Architected platform infrastructure with Java/Python microservices, designing data models, storage layers, and integration APIs for complex enterprise domains, sustaining 99.99% uptime for 5K+ internal users.",
"Built data pipelines turning unstructured operational data into searchable knowledge across ingestion, transformation, and serving layers, enabling downstream ML and analytics use cases.",
"Implemented access-controlled, policy-aware data systems with role-based permissions and audit logging, ensuring the right context reached the right consumers securely.",
"Introduced workflow orchestration and scheduling (Airflow, cron) with experiment tracking and reproducibility tooling, cutting manual processing time by 60% for analytics workflows.",
"Led a 4-person multi-disciplinary team through architecture and tradeoff decisions, driving cloud-native adoption that cut infrastructure cost by 35%."
]}
];

const projects=[
["AgentFlow","Agent orchestration with tool calling, retrieval, memory, and human validation.","Agents","https://github.com/devthedevil/openAI-Agent-SDK","https://github.com/devthedevil/openAI-Agent-SDK#readme"],
["AskMyStore","LangGraph retail RAG with multi-step reasoning and grounded responses.","RAG","https://github.com/devthedevil/AskMyStore","https://ask-my-store.vercel.app/"],
["LangChain Search","Search-grounded chat connecting LLM reasoning with current context.","RAG","https://github.com/devthedevil/LangChain-Chat-with-Search","https://github.com/devthedevil/LangChain-Chat-with-Search#readme"],
["Model Context Protocol","Experiments connecting models to structured tools and governed context.","Agents","https://github.com/devthedevil/MCP","https://github.com/devthedevil/MCP#readme"],
["TradeSentinel","AI-assisted market intelligence with live signals and actionable workflows.","Product","https://github.com/devthedevil/tradesentinel","https://tradesentinel.vercel.app/"],
["Real-time Stock Pipeline","Kafka and cloud pipeline transforming streaming events into intelligence.","Data","https://github.com/devthedevil/Realtime-Stock-Market-Analysis","https://github.com/devthedevil/Realtime-Stock-Market-Analysis#readme"],
["CME MDP 3.0 Feed Handler","Low-latency multicast ingestion engineered for precise market data.","Systems","https://github.com/devthedevil/CME-Multicast-Market-Data-Feed-Handler-C-","https://github.com/devthedevil/CME-Multicast-Market-Data-Feed-Handler-C-#readme"],
["oxide-hv","Rust hypervisor exploration focused on safe, verifiable systems behavior.","Systems","https://github.com/devthedevil/oxide-hv","https://oxide-hv.vercel.app/"],
["Experimental Operating System","A UNIX-like OS built to understand kernels, memory, and processes.","Systems","https://github.com/devthedevil/EXPOS","https://github.com/devthedevil/EXPOS#readme"],
["Character Device Driver","Linux kernel interface connecting low-level I/O and user space.","Systems","https://github.com/devthedevil/Character-Device-Driver","https://github.com/devthedevil/Character-Device-Driver#readme"],
["16-Bit RISC Processor","Processor design tracing instructions through a working datapath.","Systems","https://github.com/devthedevil/Hardware-lab","https://github.com/devthedevil/Hardware-lab#readme"],
["STRANGERS","Interactive React storytelling shaped around responsive product experience.","Product","https://github.com/devthedevil/Strangers","https://strangers-react.vercel.app/"],
["HireLoop","Hiring workflow product for clearer, faster team decisions.","Product","https://github.com/devthedevil/hireloop","https://github.com/devthedevil/hireloop#readme"],
["Voting App on Kubernetes","Multi-service application deployed with cloud-native orchestration.","Cloud","https://github.com/devthedevil/Kubernetes-K8","https://github.com/devthedevil/Kubernetes-K8#readme"],
["Pitch Perfect","Native iOS audio application built with Swift and Apple frameworks.","Apple","https://github.com/devthedevil/Pitch_Perfect","https://github.com/devthedevil/Pitch_Perfect#readme"],
["Tic Tac Toe","Native Android application exploring interaction and state.","Product","https://github.com/devthedevil/TicTacToe-Game","https://github.com/devthedevil/TicTacToe-Game#readme"]
];
const phrases=["context with provenance","agents with judgment","knowledge that compounds","evaluation that learns"];
const stack=["Python","LangGraph","LangChain","MCP","Function Calling","RAG","Embeddings","pgvector","FastAPI","Swift","SwiftUI","AppKit","TypeScript","PostgreSQL","Kafka","Airflow","AWS","Kubernetes","Evaluation","Provenance"];

export default function Home(){const[phrase,setPhrase]=useState(0);const[filter,setFilter]=useState("All");useEffect(()=>{const t=setInterval(()=>setPhrase(p=>(p+1)%phrases.length),2200);return()=>clearInterval(t)},[]);const shown=useMemo(()=>filter==="All"?projects:projects.filter(p=>p[2]===filter),[filter]);return <main>
<nav><a className="brand" href="#top"><span>DK</span><b>APPLIED / INTELLIGENCE</b></a><div><a href="#system">System</a><a href="#experience">Experience</a><a href="#projects">Work</a></div><a className="navcta" href="mailto:devkumar.dklv@gmail.com">CONNECT ↗</a></nav>
<section className="hero" id="top"><div className="mesh"/><div className="hero-copy"><p className="eyebrow"><i/> APPLIED AI · PLATFORM INFRASTRUCTURE</p><h1>Context becomes<br/><em>capability.</em></h1><p className="dynamic">Building <span key={phrase}>{phrases[phrase]}</span></p><p className="lede">I build AI-native platforms that help engineers explore, reason, and act—connecting models to trusted knowledge, useful tools, measurable quality, and human judgment.</p><div className="actions"><a className="primary" href="#system">Enter the system <span>↓</span></a><a href="mailto:devkumar.dklv@gmail.com">devkumar.dklv@gmail.com ↗</a></div></div>
<div className="agent" aria-label="Animated agentic knowledge system diagram"><div className="agent-head"><span>TRACE / AGENT-7C21</span><b><i/> RUNNING</b></div><div className="prompt"><small>ENGINEER</small><b>Which signal changed—and why?</b></div><div className="brain"><small>ORCHESTRATOR</small><b>Reason + route</b><span>human steerable</span></div><div className="source s1"><small>POSTGRESQL</small><b>PROGRAM DATA</b></div><div className="source s2"><small>S3</small><b>ARTIFACTS</b></div><div className="source s3"><small>DOCS</small><b>KNOWLEDGE</b></div><div className="tool"><small>MCP TOOL</small><b>analyze_signal()</b></div><i className="edge e1"/><i className="edge e2"/><i className="edge e3"/><i className="edge e4"/><div className="answer"><small>GROUNDED ANSWER</small><b>3 sources · 1 tool · 91% confidence</b><span>PROVENANCE ATTACHED ✓</span></div><div className="agent-foot"><span>ACCESS / POLICY OK</span><span>HUMAN / VALIDATED</span><span>EVAL / PASS</span></div></div>
<div className="stats"><div><b>91%</b><span>ANSWER ACCURACY</span></div><div><b>60%</b><span>FASTER DISCOVERY</span></div><div><b>15h+</b><span>SAVED WEEKLY</span></div><div><b>99.99%</b><span>PLATFORM UPTIME</span></div></div></section>

<section className="system" id="system"><header><div><p className="kicker">01 / INTELLIGENCE SYSTEM</p><h2>Trust is part of<br/><em>the architecture.</em></h2></div><p>Useful AI is more than a model call. It is context selection, policy enforcement, tool orchestration, reproducible analysis, evaluation, and a clear place for human judgment.</p></header><div className="flow">{[["01","KNOWLEDGE","ingest · embed · index"],["02","POLICY","identify · authorize"],["03","AGENT","plan · call · observe"],["04","PROVENANCE","trace · reproduce"],["05","EVALUATE","measure · improve"],["06","HUMAN","steer · validate"]].map((x,i)=><div key={x[1]}><span>{x[0]}</span><i/><b>{x[1]}</b><small>{x[2]}</small>{i<5&&<em>→</em>}</div>)}</div><div className="principles"><article><span>01</span><h3>Context at the right moment</h3><p>Data models, retrieval, and access boundaries determine whether an AI system is genuinely useful—or merely fluent.</p></article><article><span>02</span><h3>Agents that remain steerable</h3><p>Multi-step automation accelerates work while checkpoints keep experts in control of consequential decisions.</p></article><article><span>03</span><h3>Learning encoded as infrastructure</h3><p>Evaluations, feedback, traces, and monitoring turn each run into evidence for the next better version.</p></article></div></section>

<section className="experience" id="experience"><header><p className="kicker">02 / EXPERIENCE</p><h2>Platforms people<br/><em>depend on.</em></h2></header><div className="timeline">{experience.map((job,j)=><article key={job.company}><div className="job"><span>0{j+1}</span><div><h3>{job.company}</h3><p>{job.role}</p></div><div><b>{job.date}</b><small>{job.place}</small></div></div><ol>{job.bullets.map((b,i)=><li key={b}><span>{String(i+1).padStart(2,"0")}</span><p>{b}</p></li>)}</ol></article>)}</div></section>

<section className="eval"><div><p className="kicker">03 / FEEDBACK LOOP</p><h2>Measure the answer.<br/><em>Improve the system.</em></h2><p>Evaluation is a product surface. Automated checks and expert feedback make quality visible, comparable, and actionable.</p></div><div className="evalboard"><div className="eval-head"><span>PRODUCTION EVAL / 30 DAYS</span><b>QUALITY ↑</b></div><div className="metric"><span>END-TO-END ACCURACY</span><strong>72%</strong><i>→</i><strong>91%</strong></div><div className="curve">{[24,29,27,36,42,40,51,58,67,75,83,91].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div><div className="eval-foot"><span>AUTOMATED EVALS</span><span>HUMAN FEEDBACK</span><span>REGRESSION MONITORING</span></div></div></section>

<section className="projects" id="projects"><header><div><p className="kicker">04 / OPEN SYSTEMS LAB</p><h2>Go beyond<br/><em>the tutorial.</em></h2></div><p>Agents, retrieval, streaming data, kernels, native clients, and cloud systems—each project deepens the understanding needed to ship AI across real boundaries.</p></header><div className="filters">{["All","Agents","RAG","Data","Systems","Product","Cloud","Apple"].map(f=><button key={f} className={filter===f?"active":""} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="cards">{shown.map((p,i)=><article key={p[0]}><div className="cardhead"><span>{String(i+1).padStart(2,"0")}</span><b>{p[2]}</b></div><div className="nodes"><i/><i/><i/><i/><span/></div><h3>{p[0]}</h3><p>{p[1]}</p><div className="links"><a href={p[3]} target="_blank" rel="noreferrer">Source code ↗</a><a href={p[4]} target="_blank" rel="noreferrer">{p[4].includes("#readme")?"Technical demo":"Live demo"} ↗</a></div></article>)}</div></section>

<section className="toolkit"><p className="kicker">05 / TOOLKIT</p><div className="ticker"><div>{[...stack,...stack].map((x,i)=><span key={i}>{x}<i>◆</i></span>)}</div></div><div className="toolgrid"><article><span>INTELLIGENCE</span><h3>Models connected to work</h3><p>Agentic pipelines, RAG, embeddings, vector search, function calling, MCP, evaluation, feedback loops and cloud AI services.</p></article><article><span>INFRASTRUCTURE</span><h3>Context engineered to last</h3><p>Backend services, data pipelines, PostgreSQL, S3, Kafka, Airflow, provenance, policy-aware access, CI/CD and Kubernetes.</p></article><article><span>EXPERIENCE</span><h3>Capabilities in people’s hands</h3><p>Python, FastAPI, Swift, SwiftUI, AppKit, TypeScript, API design, developer tools, CLIs and human-centered collaboration.</p></article></div></section>

<section className="research"><div><p className="kicker">06 / RESEARCH</p><h2>Evidence changes<br/><em>the next decision.</em></h2><p>Research and applied AI share a discipline: define what quality means, measure honestly, and preserve the evidence behind every conclusion.</p></div><article><span>IEEE PUBLICATION</span><h3>Comparative Study of Movie Recommendation Systems using Feature Engineering</h3><div className="researchviz"><i/><i/><i/><i/><b>RELEVANCE / COMPARISON</b></div><div><a href="https://ieeexplore.ieee.org/document/10094480" target="_blank" rel="noreferrer">Paper ↗</a><a href="https://github.com/devthedevil/Comparative-Study-of-Movie-Recommendation-System/blob/main/Netflix_Movie.ipynb" target="_blank" rel="noreferrer">Source ↗</a><a href="https://drive.google.com/file/d/1rayr6Cht6quyLUJOXWOAcBi_rxQp2Ol0/view" target="_blank" rel="noreferrer">Certificate ↗</a></div></article></section>

<section className="contact"><p className="kicker"><i/> READY FOR THE NEXT QUESTION</p><h2>Build intelligence<br/><em>people can trust.</em></h2><p>I’m drawn to the hard, connective work: making scattered knowledge useful, powerful tools safe, analysis reproducible, and each release more capable than the last.</p><a className="primary" href="mailto:devkumar.dklv@gmail.com">Start a conversation <span>↗</span></a><div><a href="https://github.com/devthedevil" target="_blank" rel="noreferrer">GitHub ↗</a><a href="https://leetcode.com/u/dev_kumar_dklv/" target="_blank" rel="noreferrer">LeetCode ↗</a><a href="tel:+13125328223">+1 312 532 8223</a></div></section>
</main>}
